export const skillsData = [
  { title: 'Programming Languages', icon: 'code', details: ['JavaScript', 'ES6+', 'TypeScript'] },
  { title: 'Markup and Styling Languages', icon: 'html', details: ['HTML / HTML5', 'CSS / CSS3'] },
  {
    title: 'Frameworks and Libraries',
    icon: `folder_code`,
    details: [
      `React.js`,
      `Angular`,
      `Redux`,
      `Redux Toolkit`,
      `Flux`,
      `React Bootstrap`,
      `React Router`,
      `React Query`,
      `React Hook Forms`,
      `Lodash`,
      `Underscore.js`,
      `D3.js`,
      `SVG`,
      `Highcharts`,
      `Date-fns`,
      `Moment.js`,
      `Next Js`,
      `Astro`,
      `Vue Js`,
      `NX`,
    ],
  },
  {
    title: 'API Protocols',
    icon: 'api',
    details: ['REST', 'SOAP'],
  },
  {
    title: 'Styling Frameworks and Pre-processors',
    icon: 'css',
    details: ['Bootstrap', 'Material UI', 'Tailwind CSS', 'Vuetify', 'LESS', 'SASS'],
  },
  {
    title: 'Unit Testing Frameworks and Libraries ',
    icon: `bug_report`,
    details: ['Jest', 'Enzyme', 'React Testing Library'],
  },
  { title: 'Automation Testing Frameworks', icon: 'automation', details: ['Cypress', 'Playwright'] },
  { title: 'Version Control', icon: `folder_data`, details: ['Git'] },
  { title: 'Version Control Systems', icon: `identity_platform`, details: ['Bitbucket', 'GitHub', 'GitLab'] },
  { title: 'CI/CD Tools', icon: `all_inclusive`, details: [`Jenkins`, `GitLab`, `Bamboo`] },
  {
    title: 'Development Tools',
    icon: `developer_mode_tv`,
    details: ['Visual Studio Code', 'Sublime Text', 'IntelliJ IDEA', 'Eclipse IDE', 'Spring Tool Suite', 'Android Studio'],
  },
  {
    title: 'Others',
    icon: `developer_guide`,
    details: [
      `Object Oriented Programming in Java (OOPS)`,
      `Database Management System (DBMS)`,
      `Data Structures and Algorithms (DSA)`,
      `UI/UX Design`,
      `Docker`,
      `Agile SDLC`,
      `JIRA`,
      `Confluence`,
      `Rally`,
      `ServiceNow`,
      `Veracode`,
      `Glassbox`,
      `Launch Darkly`,
      `Sumo Logic`,
      `Invision`,
      `Figma`,
      `Sketch`,
      `Flutter`,
      `Dart`,
      `NPM`,
      `Yarn`,
      `Node JS`,
      `SonarQube`,
      `Black Duck`,
      `Webpack`,
      `Vite`,
      `Python`,
      `SQL`,
    ],
  },
];
