export const certificateData = [
  {
    title: `Generative AI for Beginners`,
    issuer: `Udemy`,
    date: `Aug 2025`,
    url: `https://www.udemy.com/certificate/UC-d84690ab-b974-4289-b830-71d3edb961b7/`,
    image: `/assets/gen-ai-beginners.jpg`,
  },
  {
    title: `Frontend Developer (React)`,
    issuer: `HackerRank`,
    date: `Dec 2024`,
    url: `https://www.hackerrank.com/certificates/iframe/3f19f740257a`,
    image: `/assets/frontend_cert.png`,
  },
  {
    title: `JavaScript (Intermediate)`,
    issuer: `HackerRank`,
    date: `Jun 2022`,
    url: `https://www.hackerrank.com/certificates/iframe/b85869fe3219`,
    image: `/assets/js_intermediate.png`,
  },
  {
    title: `JavaScript (Basic)`,
    issuer: `HackerRank`,
    date: `Apr 2022`,
    url: `https://www.hackerrank.com/certificates/iframe/697e775267fc`,
    image: `/assets/js_basic.png`,
  },
  {
    title: `React (Basic)`,
    issuer: `HackerRank`,
    date: `Apr 2022`,
    url: `https://www.hackerrank.com/certificates/iframe/726a59a11bf4`,
    image: `/assets/react_basic.png`,
  },
  {
    title: `Commercial Application Development in Android`,
    issuer: `Apsolutio`,
    date: `Aug 2019`,
    url: ``,
  },
  {
    title: `Introduction to R Software`,
    issuer: `IIT Kanpur`,
    date: `Mar 2019`,
    url: ``,
  },
  {
    title: `Programming, Data Structures and Algorithms using Python`,
    issuer: `IIT Madras`,
    date: `Aug 2018`,
    url: ``,
  },
];
